""" Plugin manager {{{

if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

""" }}}

""" Plugins {{{

call plug#begin('~/.vim/plugged')

    " Colorscheme
    Plug 'nanotech/jellybeans.vim'

    " Statusline
    Plug 'itchyny/lightline.vim'

    " Highlight indent
    Plug 'Yggdroot/indentLine'

    " Autoclose brackets
    Plug 'raimondi/delimitmate'

call plug#end()

""" }}}

""" General settings {{{

    set nocompatible
    filetype plugin indent on
    syntax on
    set encoding=utf-8
    set clipboard=unnamedplus
    set hidden
    autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

    set splitbelow
    set splitright
    
    set foldmethod=marker
    set confirm
    set noautowrite

    set autoindent
    set tabstop=8
    set shiftwidth=4
    set softtabstop=4
    set shiftround
    set expandtab
    set smarttab

    set backspace=indent,eol,start

    set ttyfast
    set lazyredraw

""" }}}

""" Interface {{{

    set background=dark
    silent! colorscheme jellybeans

    set number              " Show line number
    set numberwidth=5       " Line number width
    set title               " Show filename on title
    set noshowmode          " Hide mode
    set nowrap
    set scrolloff=5         " Line after cursor
    set laststatus=2        " Always show statusline

""" }}}

""" Key binddings {{{

    " Leader
    let mapleader = " "

    nnoremap <Leader>w :update<cr>

""" }}}

""" Custom command {{{

""" }}}

""" Plugin settings {{{

    " Lightline
    let g:lightline = {
        \ 'colorscheme': 'jellybeans',
        \ }

    " Indentline
    let g:indentLine_char = '│'
    
""" }}}

